# monitor=DP-2,2560x1440@143.97,0x0,1.0,bitdepth,10, vrr, 2, cm , srgb

monitorv2 {
  output = DP-2
  mode = 2560x1440@143.97
  position = 0x0
  scale = 1.0
  bitdepth = 10
  vrr = 0
  cm = srgb
}

# monitor=HDMI-A-2,3840x2160@60.0,0x0,2.67,bitdepth,10, vrr, 0, sdrbrightness, 1.0, sdrsaturation, 0.5
monitorv2 {
  output = HDMI-A-2
  mode = 3840x2160@60
  position = auto-up
  scale = 2.67
  bitdepth = 10
  vrr = 0
  sdr_min_luminance = 0.005
  sdr_max_luminance = 80
  sdrsaturation = 0.5
  sdrbrightness = 1.0c 
}

