monitorv2 {
  output = DP-2
  mode = 2560x1440@144
  position = auto-right
  scale = 1
  # bitdepth = 10
  vrr = 0
  cm = srgb
  # icc = /home/joseph/Documents/lg_27gl850_native.icc
}

monitorv2 {
  output = DP-1
  mode = 3840x2160@160
  position = 0x0
  scale = 1
  scale = 1.333
  bitdepth = 10
  vrr = 3
  cm = srgb
  # cm = hdr
  sdr_min_luminance = 0.005
  sdr_max_luminance = 80
  sdrsaturation = 0.8
  sdrbrightness = 1.2
}

monitorv2 {
  output = HDMI-A-2
  mode = 3840x2160@60
  # mode = 3840x2160@120
  position = auto-up
  scale = 2.67
  bitdepth = 10
  vrr = 0
  cm = srgb
  sdr_min_luminance = 0.005
  sdr_max_luminance = 80
  sdrsaturation = 1.0
  sdrbrightness = 1.0
}

